### ISSUE TITLE
Mini V 2 with ESP32 is not working with this adapter

### ISSUE THREAD

**Issue by Markus7501** [DrozmotiX/ioBroker.wlanthermo-nano#10]
**Describe the bug**  

**To Reproduce**  
1. Connect Mini with ESP. Only name is snyced, but no values.

2. See  MQTT log: 
{"system":{"time":"1597589284","unit":"C","rssi":-54,"online":2},"channel":[{"number":1,"name":"Pitmaster","typ":0,"temp":999.00,"min":79.00,"max":88.00,"alarm":0,"color":"#0000FF","fixed":false,"connected":false},{"number":2,"name":"Roastbeef","typ":0,"temp":999.00,"min":10.00,"max":56.00,"alarm":0,"color":"#22B14C","fixed":false,"connected":false},{"number":3,"name":"Kanal 3","typ":0,"temp":999.00,"min":90.00,"max":110.00,"alarm":0,"color":"#EF562D","fixed":false,"connected":false},{"number":4,"name":"Kanal4","typ":0,"temp":999.00,"min":10.00,"max":350.00,"alarm":0,"color":"#FFC100","fixed":false,"connected":false},{"number":5,"name":"Kanal 5","typ":0,"temp":999.00,"min":77.00,"max":90.00,"alarm":0,"color":"#A349A4","fixed":false,"connected":false},{"number":6,"name":"Kanal5","typ":0,"temp":999.00,"min":105.00,"max":115.00,"alarm":0,"color":"#804000","fixed":false,"connected":false},{"number":7,"name":"Kanal 7","typ":0,"temp":999.00,"min":10.00,"max":35.00,"alarm":0,"color":"#5587A2","fixed":false,"connected":false},{"number":8,"name":"Kanal8","typ":0,"temp":999.00,"min":10.00,"max":53.00,"alarm":0,"color":"#FF9B69","fixed":false,"connected":false},{"number":9,"name":"Kanal 9","typ":15,"temp":999.00,"min":10.00,"max":35.00,"alarm":0,"color":"#5C7148","fixed":true,"connected":false},{"number":10,"name":"Kanal 10","typ":15,"temp":999.00,"min":10.00,"max":35.00,"alarm":0,"color":"#5C7148","fixed":true,"connected":false},{"number":11,"name":"Kanal 11","typ":17,"temp":999.00,"min":10.00,"max":35.00,"alarm":0,"color":"#5C7148","fixed":true,"connected":false},{"number":12,"name":"Kanal 12","typ":17,"temp":999.00,"min":10.00,"max":54.00,"alarm":0,"color":"#5C7148","fixed":true,"connected":false}],"pitmaster":{"type":["off","manual","auto"],"pm":[{"id":0,"channel":5,"pid":2,"value":100,"set":88.00,"typ":"manual","set_color":"#ff0000","value_color":"#000000"},{"id":1,"channel":2,"pid":2,"value":0,"set":50.00,"typ":"off","set_color":"#FE2EF7","value_color":"#848484"}]}}

**Expected behavior**  
Mini with ESP32 is also working

**Comment by DutchmanNL** [comment]
thank you, just received the new device allowing me to adjust the adapter expect to be able spending some effort in it during september

**Comment by Markus7501** [comment]
Hi,
Any update ?

**Comment by DutchmanNL** [comment]
> Hi,
> Any update ?
> if you need support to test something, please feel free to contact me.

will be updated within the next 2weeks

**Comment by DutchmanNL** [comment]
solved 60e3ee8f76b9735dc713f456cd164b7c964e5cb2
