### ISSUE TITLE
Log wird überflutet

### ISSUE THREAD

**Issue by slimline33** [DrozmotiX/ioBroker.wlanthermo-nano#163]
Hi, vielleicht bin ich ja zu blöd, aber nach aktivierung der Instanz wird mein Log überflutet mit get meldungen.

`

wlanthermo-nano.0 | 2021-04-08 19:59:33.016 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
-- | -- | -- | --
wlanthermo-nano.0 | 2021-04-08 19:59:33.011 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
wlanthermo-nano.0 | 2021-04-08 19:59:33.007 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
wlanthermo-nano.0 | 2021-04-08 19:59:33.003 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
wlanthermo-nano.0 | 2021-04-08 19:59:32.999 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
wlanthermo-nano.0 | 2021-04-08 19:59:32.994 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}
wlanthermo-nano.0 | 2021-04-08 19:59:32.990 | info | (13709) Get http function started for device : 1 array : {"1":{"Username":"admin","Password":"TR\f]\u000f","ip":"192.168.1.241","port":"80"}}

`
![08 04](https://user-images.githubusercontent.com/3323812/114074910-35870900-98a5-11eb-804c-6648b80e0749.jpg)

Benutzer admin Passwort admin.

Muss evtl. noch etwas im Wlanthermo aktiviert werden? Der Adapter holt sich ja die Infos über die Webseite und nutzt kein mqtt oder ähnliches.

Gruß Christoph

**Versions:**  
 - Adapter version: letzte von Github
 - JS-Controller version: 5.0.1.4
 - Node version: v12.20.1
 - Operating system: Debian 9 auf VM

**Comment by styrmirgruenheit** [comment]
Ich habe mal einen Blick in den Code geworfen. Für die Intervall-Abstände wird eine falsche Variable aus der Konfiguration genommen. Intervall-Zeit ist dadurch NaN. Dadurch ist keine Pause zwischen den Ausführungen.

`const intervall_time = this.config.Time_Sync * 1000;`

Sollte aber `const intervall_time = this.config.intervallTime * 1000;` sein.

**Comment by styrmirgruenheit** [comment]
Ich habe einen Pullrequest erstellt, der die Probleme behebt: https://github.com/DrozmotiX/ioBroker.wlanthermo-nano/pull/186

**Comment by slimline33** [comment]
Danke. Ich teste das bei Gelegenheit

**Comment by slimline33** [comment]
Entschuldigt bitte die späte Rückmeldung. Es läuft wieder einwandfrei im iobroker! Danke !
