### ISSUE TITLE
change of DPs .type .alarm without function

### ISSUE THREAD

**Issue by darkiop** [DrozmotiX/ioBroker.wlanthermo-nano#6]
Change data points .type and .alarm without function. The change will not be sent to wlanthermo (if you log in debugmode you can see the changes of the other DPs - they work).

**Comment by darkiop** [comment]
@DutchmanNL Did you get a chance to look at the problem? In addition to the two data points mentioned, there is also the .color - this one doesn't like either :)

**Comment by DutchmanNL** [comment]
working on it currently updating 11 adapter to controller 3.0 :/

**Comment by darkiop** [comment]
oh ok :) No hurry - it's only cosmetics. But good to know you have it on your list. Have a nice Sunday!

**Comment by micklafisch** [comment]
i can confirm this behavior. I cannot change the DP "alarm" via iobroker also the color will be set to "0" if i change the DP "color" via iobroker. greetings, michael

**Comment by DutchmanNL** [comment]
Update : agreed the following with the WLANthermo vendor : 

- we will update the adapter to allow settings alarms
- confirming an alarm can only be done on the device itself

so in a feature release I will ensure changes to the data points will be reflected to WlanThermo, but please be aware an alarm can only be turned off at the device itself (which is agreed as functional design with WlanThermo

**Comment by sochs** [comment]
An alarm is always calculated and executed on the end device/system (e.g. iobroker) so that it can also be quit there. Only the type of alarm on the thermometer itself can be set via the API (no alarm, push and / or buzzer).

**Comment by DutchmanNL** [comment]
starting from version 0.2.0-beta.1  type of alarm  can be set (no alarm, push and / or buzzer).

**Comment by DutchmanNL** [comment]
oh and btw, if you have the alarm set to buzzer and it goes of, you can change it to disable which will disable (not confirm!) the alert at the devic
